apiVersion: v1
kind: Service
metadata:
  name: {{ include "myfastapiapp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "myfastapiapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "myfastapiapp.selectorLabels" . | nindent 4 }}
