name: CICD Pipeline 

on:
  push:
    branches:
      - '**'
    paths:
      - 'server/**' 

env:
  IMAGE_NAME: myfastapiapp
  CHART_NAME: myfastapiapp
  CHART_VERSION: 0.1.0
  
jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r server/requirements.txt

      - name: Run unit tests
        run: python -m pytest --maxfail=1 --disable-warnings -q

      - name: Log in to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:pr-${{ github.sha }} ./server

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:pr-${{ github.sha }}

  deploy:
      runs-on: ubuntu-latest
      needs: build-test-push
      if: github.ref == 'refs/heads/main' 
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set Kubeconfig
          run: |
            echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/kubeconfig
            export KUBECONFIG=$HOME/kubeconfig

        - name: Helm login
          run: helm registry login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

        - name: Pull Helm chart
          run: helm pull oci://${{ secrets.ACR_LOGIN_SERVER }}/helm/${{ env.CHART_NAME }} --version ${{ env.CHART_VERSION }} --untar

        - name: Deploy Helm chart
          run: |
            helm upgrade --install ${{ env.CHART_NAME }} ./${{ env.CHART_NAME }} \
              --set image.repository=${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }} \
              --set image.tag=pr-${{ github.sha }}
